DROP TABLE IF EXISTS STOCK;

CREATE TABLE STOCK ( 
id INT AUTO_INCREMENT  PRIMARY KEY,
symbol VARCHAR(16) NOT NULL , 
bid_price DECIMAL(20, 2) NOT NULL , 
ask_price DECIMAL(20, 2) NOT NULL , 
event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);